In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame,Series

In [2]:
row_idx_arr = list(zip(['r0', 'r0'], ['r-00', 'r-01']))
row_idx = pd.MultiIndex.from_tuples(row_idx_arr)
 
# Column Multi-Index
col_idx_arr = list(zip(['c0', 'c0', 'c1'], ['c-00', 'c-01', 'c-10']))
col_idx = pd.MultiIndex.from_tuples(col_idx_arr)
 
# Create the DataFrame
d = DataFrame(np.arange(6).reshape(2,3), index=row_idx, columns=col_idx)
d = d.applymap(lambda x: (x // 3, x % 3))

In [3]:
d.stack()

c0      c1
r0 r-00 c-00  (0, 0)     NaN
        c-01  (0, 1)     NaN
        c-10     NaN  (0, 2)
   r-01 c-00  (1, 0)     NaN
        c-01  (1, 1)     NaN
        c-10     NaN  (1, 2)

In [4]:
d.unstack()

c0                              c1        
      c-00            c-01            c-10        
      r-00    r-01    r-00    r-01    r-00    r-01
r0  (0, 0)  (1, 0)  (0, 1)  (1, 1)  (0, 2)  (1, 2)

In [5]:
from collections import OrderedDict
from pandas import DataFrame
import pandas as pd
import numpy as np
 
table = OrderedDict((
    ("Item", ['Item0', 'Item0', 'Item1', 'Item1']),
    ('CType',['Gold', 'Bronze', 'Gold', 'Silver']),
    ('USD',  ['1$', '2$', '3$', '4$']),
    ('EU',   ['1€', '2€', '3€', '4€'])
))
d = DataFrame(table)

In [6]:
d

Item   CType USD  EU
0  Item0    Gold  1$  1€
1  Item0  Bronze  2$  2€
2  Item1    Gold  3$  3€
3  Item1  Silver  4$  4€

In [7]:
d.pivot(index='Item', columns='CType',values='USD')

CType Bronze Gold Silver
Item                    
Item0     2$   1$   None
Item1   None   3$     4$

In [11]:
d

Item   CType USD  EU
0  Item0    Gold  1$  1€
1  Item0  Bronze  2$  2€
2  Item1    Gold  3$  3€
3  Item1  Silver  4$  4€

In [13]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
s = np.where(arr%2 == 0,1,0)
s

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [19]:
arr > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [21]:
big5 = arr[arr > 5]

In [24]:
arr[arr[big5]] = 10

IndexError: index 6 is out of bounds for axis 0 with size 3

In [25]:
vector = np.array([5, 10, 15, 20])

In [27]:
equal_five_ten = (vector == 5) | (vector == 10)
equal_five_ten

array([ True,  True, False, False], dtype=bool)

In [28]:
vector[equal_five_ten] = 10
vector

array([10, 10, 15, 20])

In [29]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
big5 = (arr > 5)
big5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [31]:
arr[big5] = 10
arr

array([[ 0,  1,  2,  3],
       [ 4,  5, 10, 10],
       [10, 10, 10, 10]])

In [32]:
arr[:,2]

array([ 2, 10, 10])

In [34]:
arr.*max*?

In [35]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5, 10, 10],
       [10, 10, 10, 10]])

In [36]:
arr.rank()

AttributeError: 'numpy.ndarray' object has no attribute 'rank'

In [37]:
df = DataFrame(np.random.randn(4,3))
df

0         1         2
0  0.702216 -1.270228  0.274247
1 -0.179506 -0.178434 -0.887600
2  0.530488  0.987230 -1.559187
3 -0.459065 -0.575194  0.562246

In [38]:
df.rank()

0    1    2
0  4.0  1.0  3.0
1  2.0  3.0  2.0
2  3.0  4.0  1.0
3  1.0  2.0  4.0

In [39]:
df.ix[0,2] = np.nan
df

0         1         2
0  0.702216 -1.270228       NaN
1 -0.179506 -0.178434 -0.887600
2  0.530488  0.987230 -1.559187
3 -0.459065 -0.575194  0.562246

In [40]:
df.rank()

0    1    2
0  4.0  1.0  NaN
1  2.0  3.0  2.0
2  3.0  4.0  1.0
3  1.0  2.0  3.0